name:         Machines in the Valley
description:  A digital history project by Jason A. Heppler.
markdown:     kramdown
highlighter:  pygments
url:          http://dissertation.jasonheppler.org # leave blank when working locally
repo:         https://github.com/hepplerj/machinesvalley/

# Owner/author information
owner:
  name:           Jason Heppler
  avatar:         photo.jpg
  email:          jason@jasonheppler.org
  twitter:        "jaheppler"
  instagram:      "hepplerj"
  github:         "hepplerj"
  facebook:       "jason.heppler"
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    "http://plus.google.com/112447146120355094986"

permalink:      /:year/:month/:day/:title/

links:
  - title: Introduction
    url: /introduction/
  - title: Stories
    url: /studies/
  - title: Views
    url: /visualizations/
  - title: Data
    url: /data/
