name:         Machines in the Valley
description:  A digital history project by Jason A. Heppler.
url:          https://machinesinthevalley.org
repo:         https://github.com/hepplerj/machinesvalley/

# Owner/author information
owner:
  name:           Jason Heppler
  avatar:         photo.jpg
  email:          jason@jasonheppler.org
  github:         "hepplerj"

permalink:      /:year/:month/:day/:title/

links:
  - title: Overview
    url: /introduction/
  - title: Views
    url: /visualizations/
  - title: Data
    url: /data/
